insert into genre values (000, '총류');
insert into genre values (010, '도서학, 서지학');
insert into genre values (020, '문헌정보학');
insert into genre values (030, '백과사전');
insert into genre values (040, '일반 논문집');
insert into genre values (050, '일반 연속간행물');
insert into genre values (060, '일반 학회, 단체, 협회, 기관');
insert into genre values (070, '신문, 언론, 저널리즘');
insert into genre values (080, '일반 전집, 총서');
/*insert into genre values (090, '');*/
insert into genre values (100, '철학');
insert into genre values (110, '형이상학');
/*insert into genre values (120, '');*/
insert into genre values (130, '철학의 세계');
insert into genre values (140, '경학');
insert into genre values (150, '아시아(동양)철학, 사상');
insert into genre values (160, '서양철학');
insert into genre values (170, '논리학');
insert into genre values (180, '심리학');
insert into genre values (190, '윤리학, 도덕철학');
insert into genre values (200, '종교');
insert into genre values (210, '비교종교학');
insert into genre values (220, '불교');
insert into genre values (230, '기독교');
insert into genre values (240, '도교');
insert into genre values (250, '천도교');
insert into genre values (260, '신도');
insert into genre values (270, '바라문교, 인도교');
insert into genre values (280, '회교(이슬람교)');
insert into genre values (290, '기타 제종교');
insert into genre values (300, '사회과학');
insert into genre values (310, '통계학');
insert into genre values (320, '경제학');
insert into genre values (330, '사회학, 사회문제');
insert into genre values (340, '정치학');
insert into genre values (350, '행정학');
insert into genre values (360, '법학');
insert into genre values (370, '교육학');
insert into genre values (380, '풍속, 민속학');
insert into genre values (390, '국방, 군사학');
insert into genre values (400, '순수과학');
insert into genre values (410, '수학');
insert into genre values (420, '물리학');
insert into genre values (430, '화학');
insert into genre values (440, '천문학');
insert into genre values (450, '지학');
insert into genre values (460, '광물학');
insert into genre values (470, '생물과학');
insert into genre values (480, '식물학');
insert into genre values (490, '동물학');
insert into genre values (500, '기술과학');
insert into genre values (510, '의학');
insert into genre values (520, '농업, 농학');
insert into genre values (530, '공학, 공업일반');
insert into genre values (540, '건축공학');
insert into genre values (550, '기계공학');
insert into genre values (560, '전기공학, 전자공학');
insert into genre values (570, '화학공학');
insert into genre values (580, '제조업');
insert into genre values (590, '가정학 및 가정생활');
insert into genre values (600, '예술');
insert into genre values (610, '건축술');
insert into genre values (620, '조각');
insert into genre values (630, '공예, 장식미술');
insert into genre values (640, '서예');
insert into genre values (650, '회화, 도화');
insert into genre values (660, '사진술');
insert into genre values (670, '음악');
insert into genre values (680, '연극');
insert into genre values (690, '오락, 운동');
insert into genre values (700, '언어');
insert into genre values (710, '한국어');
insert into genre values (720, '중국어');
insert into genre values (730, '일본어');
insert into genre values (740, '영어');
insert into genre values (750, '독일어');
insert into genre values (760, '프랑스어');
insert into genre values (770, '스페인어');
insert into genre values (780, '이탈리아어');
insert into genre values (790, '기타 제어');
insert into genre values (800, '문학');
insert into genre values (810, '한국문학');
insert into genre values (820, '중국문학');
insert into genre values (830, '일본문학');
insert into genre values (840, '영미문학');
insert into genre values (850, '독일문학');
insert into genre values (860, '프랑스문학');
insert into genre values (870, '스페인문학');
insert into genre values (880, '이탈리아문학');
insert into genre values (890, '기타 제문학');
insert into genre values (900, '역사');
insert into genre values (910, '아시아(아세아)');
insert into genre values (920, '유럽(구라파)');
insert into genre values (930, '아프리카');
insert into genre values (940, '북아메리카(북미)');
insert into genre values (950, '남아메리카(남미)');
insert into genre values (960, '오세아니아(대양주)');
insert into genre values (970, '양극지방');
insert into genre values (980, '지리');
insert into genre values (990, '전기');
